# These are supported funding model platforms

github: GorillaPool
custom: https://junglebus.gorillapool.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=go-junglebus&utm_term=go-junglebus&utm_content=go-junglebus
