---
extends: relaxed

rules:
  # Don't require --- at start of files
  document-start: disable
  
  # Don't be so strict about comments
  comments:
    min-spaces-from-content: 1
    require-starting-space: false
    level: warning
  
  comments-indentation: disable
  
  # Don't be strict about truthy values
  truthy:
    check-keys: false
    allowed-values: ['true', 'false', 'on', 'off']
    level: warning
  
  # Other common annoyances
  trailing-spaces: disable
  line-length: disable
  new-line-at-end-of-file: disable
  indentation: disable
  braces: disable
  brackets: disable
